openapi: 3.0.0
info:
    title: TicTactics API
    version: 1.0.0
    description: "TicTactics API"
tags:
    - name: auth
      description: Authorization Service
    - name: users
      description: User Management Service
    - name: game
      description: Game Management Service
paths:
    /signup:
        post:
            operationId: SignUp
            tags:
                - auth
            summary: Create new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignUpRequest'
            responses:
                '200':
                    description: OK
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /signin:
        post:
            operationId: SignIn
            tags:
                - auth
            summary: Sign in
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignInRequest'
            responses:
                '200':
                    description: OK
                    headers:
                        Set-Cookie:
                            schema:
                                type: string
                                description: Session cookie
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SignInResponse'
                '401':
                    description: Invalid credentials
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedError'
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /signout:
        delete:
            operationId: SignOut
            tags:
                - auth
            summary: Sign out
            security:
                - cookieAuth: []
            responses:
                '200':
                    description: OK
                '401':
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedError'
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /deleteAccount:
        delete:
            operationId: DeleteAccount
            tags:
                - auth
            summary: Delete account
            security:
                - cookieAuth: []
            responses:
                '200':
                    description: OK
                '401':
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedError'
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /users:
        get:
            operationId: GetUsers
            tags:
                - users
            summary: Get users with a given name
            parameters:
              - in: query
                name: name
                schema:
                  type: string
            security:
                - cookieAuth: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/UserData'
                '401':
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedError'
                default:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: session

    schemas:
        # errors
        Error:
            type: object
            properties:
                error:
                    type: string

        UnauthorizedError:
            description: Access token is missing or invalid

        # types
        Credentials:
            type: object
            required:
                - name
                - password
                - email
            properties:
                name:
                    type: string
                email:
                    type: string
                password:
                    type: string
                phone:
                    type: string
        
        UserData:
            type: object
            required:
                - ELO
            properties:
                userId:
                    type: string
                username:
                    type: string
                ELO:
                    type: number

        # auth
        SignUpRequest:
            type: object
            required:
                - credentials
            properties:
                credentials:
                    $ref: '#/components/schemas/Credentials'

        SignInRequest:
            type: object
            required:
                - credentials
            properties:
                credentials:
                    $ref: '#/components/schemas/Credentials'

        SignInResponse:
            type: object
            required:
                - token
            properties:
                token:
                    type: string
